// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckIfAuthenticated():Promise<boolean>;

export function CheckMinecraftRunning():Promise<boolean>;

export function FrontendReady():Promise<void>;

export function GetUserData():Promise<main.UserData>;

export function GoogleAuth():Promise<string>;

export function PushIfAhead():Promise<void>;

export function SaveUserData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UserAuthCode(arg1:string):Promise<void>;
