// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMinecraftRunning(arg1) {
  return window['go']['main']['App']['CheckMinecraftRunning'](arg1);
}

export function CloudUpload(arg1) {
  return window['go']['main']['App']['CloudUpload'](arg1);
}
