// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfAuthenticated():Promise<boolean>;

export function CheckMinecraftRunning(arg1:string):Promise<boolean>;

export function CloudUpload(arg1:string,arg2:string):Promise<Array<string>>;

export function GetWorlds(arg1:string):Promise<Array<string>>;

export function GoogleAuth():Promise<string>;

export function UserAuthCode(arg1:string):Promise<void>;
