// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfAuthenticated() {
  return window['go']['main']['App']['CheckIfAuthenticated']();
}

export function CheckMinecraftRunning(arg1) {
  return window['go']['main']['App']['CheckMinecraftRunning'](arg1);
}

export function CloudUpload(arg1, arg2) {
  return window['go']['main']['App']['CloudUpload'](arg1, arg2);
}

export function GetWorlds(arg1) {
  return window['go']['main']['App']['GetWorlds'](arg1);
}

export function GoogleAuth() {
  return window['go']['main']['App']['GoogleAuth']();
}

export function UserAuthCode(arg1) {
  return window['go']['main']['App']['UserAuthCode'](arg1);
}
