name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Node.js (for frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Add Go bin to PATH
        run: echo "$HOME\\go\\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build app
        run: wails build

      - name: Upload built executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: build\bin\*.exe

